package com.example.hueandyou.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

// Generated with Material Theme Builder (default settings). Used only when dynamic color is unavailable.
val primaryLight = Color(0xFF904B3F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD4)
val onPrimaryContainerLight = Color(0xFF73342A)
val secondaryLight = Color(0xFF775651)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD4)
val onSecondaryContainerLight = Color(0xFF5D3F3A)
val tertiaryLight = Color(0xFF6F5C2E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFBE0A6)
val onTertiaryContainerLight = Color(0xFF564519)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF231918)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF231918)
val surfaceVariantLight = Color(0xFFF5DDD9)
val onSurfaceVariantLight = Color(0xFF534340)
val outlineLight = Color(0xFF857370)
val outlineVariantLight = Color(0xFFD8C2BE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E2C)
val inverseOnSurfaceLight = Color(0xFFFFEDEA)
val inversePrimaryLight = Color(0xFFFFB4A7)
val surfaceDimLight = Color(0xFFE8D6D3)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EE)
val surfaceContainerLight = Color(0xFFFCEAE7)
val surfaceContainerHighLight = Color(0xFFF7E4E1)
val surfaceContainerHighestLight = Color(0xFFF1DFDB)
val primaryDark = Color(0xFFFFB4A7)
val onPrimaryDark = Color(0xFF561E16)
val primaryContainerDark = Color(0xFF73342A)
val onPrimaryContainerDark = Color(0xFFFFDAD4)
val secondaryDark = Color(0xFFE7BDB6)
val onSecondaryDark = Color(0xFF442925)
val secondaryContainerDark = Color(0xFF5D3F3A)
val onSecondaryContainerDark = Color(0xFFFFDAD4)
val tertiaryDark = Color(0xFFDDC48C)
val onTertiaryDark = Color(0xFF3D2E04)
val tertiaryContainerDark = Color(0xFF564519)
val onTertiaryContainerDark = Color(0xFFFBE0A6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1110)
val onBackgroundDark = Color(0xFFF1DFDB)
val surfaceDark = Color(0xFF1A1110)
val onSurfaceDark = Color(0xFFF1DFDB)
val surfaceVariantDark = Color(0xFF534340)
val onSurfaceVariantDark = Color(0xFFD8C2BE)
val outlineDark = Color(0xFFA08C89)
val outlineVariantDark = Color(0xFF534340)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DFDB)
val inverseOnSurfaceDark = Color(0xFF392E2C)
val inversePrimaryDark = Color(0xFF904B3F)
val surfaceDimDark = Color(0xFF1A1110)
val surfaceBrightDark = Color(0xFF423735)
val surfaceContainerLowestDark = Color(0xFF140C0B)
val surfaceContainerLowDark = Color(0xFF231918)
val surfaceContainerDark = Color(0xFF271D1C)
val surfaceContainerHighDark = Color(0xFF322826)
val surfaceContainerHighestDark = Color(0xFF3D3230)

// The Rate Clothing "Yes" verdict card isn't part of Material's dynamic (wallpaper-derived)
// scheme, so it gets its own fixed light/dark green rather than one of the scheme's roles.
val SuccessContainerLight = Color(0xFFC6EFCE)
val SuccessOnContainerLight = Color(0xFF0B4619)
val SuccessContainerDark = Color(0xFF1E4B2A)
val SuccessOnContainerDark = Color(0xFFB6F2C1)

internal data class SuccessColors(val container: Color, val onContainer: Color)

internal val LocalSuccessColors = staticCompositionLocalOf {
    SuccessColors(SuccessContainerLight, SuccessOnContainerLight)
}
